# Generated by Django 4.2.6 on 2023-10-30 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='loginid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
