# Generated by Django 4.2.6 on 2023-11-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransportApp', '0006_answers_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
